# Generated by Django 6.0 on 2026-01-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_w_pvsa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='geom',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
