# Generated by Django 6.0.1 on 2026-05-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_w_pvsa', '0002_lugar_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetolugar',
            name='cantidad_mala',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='objetolugar',
            name='cantidad_pendiente',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tipolugarobjetotipico',
            name='importancia',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta / Crítica')], default=1),
        ),
    ]
