# Generated by Django 6.0.1 on 2026-05-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_w_pvsa', '0003_objetolugar_cantidad_mala_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetolugar',
            name='importancia',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta / Crítica')], default=1),
        ),
    ]
