# Generated by Django 6.0.1 on 2026-05-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_w_pvsa', '0004_objetolugar_importancia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetolugar',
            name='importancia',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')], default=1),
        ),
        migrations.AlterField(
            model_name='tipolugarobjetotipico',
            name='importancia',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')], default=1),
        ),
    ]
