# Generated by Django 6.0.1 on 2026-05-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_w_pvsa', '0005_alter_objetolugar_importancia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoobjeto',
            name='cantidad_mala_anterior',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicoobjeto',
            name='cantidad_pendiente_anterior',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicoobjeto',
            name='importancia_anterior',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='historicoobjeto',
            name='minimo_operativo_anterior',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='objetolugar',
            name='minimo_operativo',
            field=models.SmallIntegerField(default=1, help_text='Cantidad mínima que debe estar funcionando para considerar aceptable este objeto.'),
        ),
        migrations.AlterField(
            model_name='objetolugar',
            name='estado',
            field=models.CharField(choices=[('B', 'Bueno'), ('P', 'Pendiente'), ('M', 'Malo')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='objetolugar',
            name='importancia',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta / Crítica')], default=1),
        ),
    ]
