# Generated by Django 6.0.5 on 2026-05-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_w_pvsa', '0006_historicoobjeto_cantidad_mala_anterior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoobjeto',
            name='estado_anterior',
            field=models.CharField(choices=[('B', 'Todo bueno'), ('P', 'Con pendientes'), ('M', 'Con unidades malas')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicoobjeto',
            name='importancia_anterior',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta / Crítica')], default=1),
        ),
        migrations.AlterField(
            model_name='objetolugar',
            name='estado',
            field=models.CharField(choices=[('B', 'Todo bueno'), ('P', 'Con pendientes'), ('M', 'Con unidades malas')], default='B', max_length=1),
        ),
    ]
