# Generated by Django 6.0 on 2026-09-17 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_w_pvsa', '0007_alter_historicoobjeto_estado_anterior_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugar',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='geom',
        ),
        migrations.DeleteModel(
            name='AreaMapa',
        ),
    ]
